apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: openshift-logging
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 1
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - effect: "NoSchedule"
        operator: Exists
        key: infra
      - effect: "NoExecute"
        operator: Exists
        key: infra
      resources:
        limits:
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 1Gi
      storage: {}
      redundancyPolicy: "ZeroRedundancy"
  visualization:
    type: "kibana"
    kibana:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - effect: "NoSchedule"
        operator: Exists
        key: infra
      - effect: "NoExecute"
        operator: Exists
        key: infra
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 1Gi
      replicas: 1
  curation:
    type: "curator"
    curator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - effect: "NoSchedule"
        operator: Exists
        key: infra
      - effect: "NoExecute"
        operator: Exists
        key: infra
      resources:
        limits:
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
      schedule: "*/5 * * * *"
  collection:
    logs:
      type: "fluentd"
      fluentd:
        tolerations:
        - operator: "Exists"
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
