apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-custom-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - resourcequotas
  - limitranges
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - '*'
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - oauths
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  - operatorgroups
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - '*'

